services:
  - type: web
    name: filter-studio-app
    env: python
    pythonVersion: 3.10.11
    buildCommand: "./build.sh"
    startCommand: "gunicorn filter_studio.wsgi:application"
    healthCheckPath: /admin/login/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: filter-studio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
      - key: EXTERNAL_DATABASE_URL
        value: postgresql://postgres:filterstudio11@db.dlfewlzybgtytibhpdkv.supabase.co:5432/postgres
      - key: CLOUDINARY_CLOUD_NAME
        value: dvn1afvqs
      - key: CLOUDINARY_API_KEY
        value: '158996543676117'
      - key: CLOUDINARY_API_SECRET
        value: 'lzbf6ULqc4crhpoHKNt-OHpXsWs'
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: filterstudio.onrender.com