services:
  - type: web
    name: filter-studio-app
    env: python
    pythonVersion: 3.10.11
    buildCommand: "./build.sh"
    startCommand: "gunicorn filter_studio.wsgi:application"
    healthCheckPath: /login/ 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: filter-studio-db 
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
      - key: EXTERNAL_DATABASE_URL
        fromSecret: EXTERNAL_DATABASE_URL
      - key: CLOUDINARY_CLOUD_NAME
        value: dvn1afvqs
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        fromSecret: CLOUDINARY_API_SECRET
        value: lzbf6ULqc4crhpoHKNt-OHpXsWs
      - key: DEBUG
        value: "False" 
      - key: ALLOWED_HOSTS
        value: https://filterstudio.onrender.com      