services:
  # هذا هو إعداد قاعدة البيانات الخاصة بك في Render
  # لن نستخدم هذا مباشرة لأنه لديك قاعدة بيانات Supabase
  # ولكن من الجيد معرفة كيف يتم إعدادها إذا احتجت إليها مستقبلاً.
  # سنركز على خدمة الويب في هذه المرحلة.

  - type: web
    name: filter-studio-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn filter_studio.wsgi:application"
    healthCheckPath: /login/ # أو أي مسار تراه مناسباً للتحقق من الصحة
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: filter-studio-db # هذا الاسم وهمي لقاعدة بيانات Render
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
      # متغيرات Supabase (قاعدة البيانات الخارجية)
      - key: EXTERNAL_DATABASE_URL
        value: postgresql://postgres:filterstudio11@db.dlfewlzybgtytibhpdkv.supabase.co:5432/postgres
      # متغيرات Cloudinary
      - key: CLOUDINARY_CLOUD_NAME
        value: dvn1afvqs
      - key: CLOUDINARY_API_KEY
        value: 158996543676117
      - key: CLOUDINARY_API_SECRET
        value: lzbf6ULqc4crhpoHKNt-OHpXsWs
      - key: DEBUG
        value: "False" # دائماً False في الإنتاج
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com # ستغير هذا لاحقاً لاسم تطبيقك الحقيقي