# Generated by Django 5.2.3 on 2025-07-07 17:40

import django.db.models.deletion
import studio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to=studio.models.user_directory_path)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to=studio.models.user_directory_path)),
                ('filter_applied', models.CharField(choices=[('crop', 'Crop'), ('grayscale', 'Grayscale'), ('invert', 'Invert'), ('sharpen', 'Sharpen'), ('count_faces', 'Count Faces'), ('blur_faces', 'Blur Faces')], max_length=50)),
                ('processing_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
