# Generated by Django 4.2.16 on 2025-07-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='filter_applied',
            field=models.CharField(choices=[('original', 'الصورة الأصلية'), ('crop', 'قص الصورة (تفاعلي)'), ('grayscale', 'تحويل إلى الرمادي'), ('invert', 'قلب الألوان'), ('sharpen', 'زيادة الحدة (تفاعلي)'), ('detect_human_face', 'التعرف على وجوه البشر'), ('blur_human_face', 'طمس وجوه البشر'), ('detect_cat_face', 'التعرف على وجوه القطط'), ('detect_eyes', 'التعرف على العيون'), ('detect_smile', 'التعرف على الابتسامات'), ('detect_full_body', 'التعرف على كامل الجسد'), ('detect_upper_body', 'التعرف على الجزء العلوي من الجسد'), ('detect_license_plate', 'التعرف على لوحات السيارات')], max_length=50),
        ),
    ]
