# Generated by Django 5.2.3 on 2025-07-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_processedimage_filter_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='filter_applied',
            field=models.CharField(choices=[('original', 'الصورة الأصلية'), ('crop', 'قص الصورة (تفاعلي)'), ('grayscale', 'تحويل إلى الرمادي'), ('invert', 'قلب الألوان'), ('sharpen', 'زيادة الحدة (تفاعلي)'), ('blur_faces', 'طمس الوجوه (AI)'), ('detect_human_face', 'التعرف على وجوه البشر (AI)'), ('detect_cat_face', 'التعرف على وجوه القطط (AI)'), ('detect_eyes', 'التعرف على العيون (AI)'), ('detect_smile', 'التعرف على الابتسامات (AI)'), ('detect_full_body', 'التعرف على كامل الجسد (AI)'), ('detect_upper_body', 'التعرف على الجزء العلوي من الجسد (AI)'), ('detect_license_plate', 'التعرف على لوحات السيارات (AI)')], max_length=50),
        ),
    ]
