"""
Django settings for filter_studio project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv
import dj_database_url
# لا حاجة لاستيراد cloudinary, cloudinary.uploader, cloudinary.api هنا إذا كنت تستخدم cloudinary_storage
# import cloudinary
# import cloudinary.uploader
# import cloudinary.api


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv(), default=[])
if DEBUG:
    ALLOWED_HOSTS += ['127.0.0.1', 'localhost']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary', # تأكد من وجود هذا.
    'studio.apps.StudioConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # تأكد من أن WhiteNoiseMiddleware بعد SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'filter_studio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'filter_studio.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# استخدم EXTERNAL_DATABASE_URL الذي قمت بتعيينه لـ Supabase
DATABASE_URL = config('EXTERNAL_DATABASE_URL')
DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL)
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')

# Cloudinary Settings
# لا تقم باستدعاء cloudinary.config() هنا مباشرة،
# بل اسمح لـ cloudinary_storage بقراءة المتغيرات من البيئة.
# تأكد من أن CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET
# موجودة كمتغيرات بيئة على Render (وهي موجودة لديك بالفعل في render.yaml و .env)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticCloudinaryStorage' # هذا هو الموصى به

# Optional: Set a specific folder for static and media files in Cloudinary
# هذه الإعدادات تتبع المعايير القياسية.
# إذا كان خطأ 400 لا يزال يظهر، فقد يكون هناك مشكلة في كيفية تعامل Cloudinary مع مجلد 'static'
# إذا لم يكن 'static' مقبولاً كجذر، ولكن هذا نادر.
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME'), # يجب قراءتها من البيئة
    'API_KEY': config('CLOUDINARY_API_KEY'), # يجب قراءتها من البيئة
    'API_SECRET': config('CLOUDINARY_API_SECRET'), # يجب قراءتها من البيئة
    'MEDIA_FOLDER': 'media',
    'STATIC_FOLDER': 'static',
    # قد تحتاج لتحديد resource_type إذا كانت الملفات ليست صوراً
    # 'STATIC_RESORCE_TYPE': 'raw', # <-- إذا كانت الملفات الثابتة ليست صورًا فقط، فقد تحتاج لهذه. لكن جرب بدونها أولاً.
}


# Authentication settings
LOGIN_URL = 'login/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'